package model;
// Generated Nov 10, 2019 9:08:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int categoryId;
     private String category;
     private Set<Products> productses = new HashSet<Products>(0);

    public Categories() {
    }

	
    public Categories(int categoryId, String category) {
        this.categoryId = categoryId;
        this.category = category;
    }
    public Categories(int categoryId, String category, Set<Products> productses) {
       this.categoryId = categoryId;
       this.category = category;
       this.productses = productses;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


