package model;
// Generated Nov 10, 2019 9:08:06 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int productId;
     private Categories categories;
     private String name;
     private String description;
     private BigDecimal price;

    public Products() {
    }

	
    public Products(int productId) {
        this.productId = productId;
    }
    public Products(int productId, Categories categories, String name, String description, BigDecimal price) {
       this.productId = productId;
       this.categories = categories;
       this.name = name;
       this.description = description;
       this.price = price;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


